### PR TITLE
add MultiTaskLassoCV and MultiTaskLasso

### PR DESCRIPTION
**Pull request by agramfort**
@mathurinm I tried to add MultiTaskLassoCV and MultiTaskLasso to help @ja-che with his experiments but the test does not end. It seems like it's not converging.

@mathurinm can you have a look?

also you'll see that mtl_path is not consistent in API with sklearn lasso_path

wdyt?

### CODE REVIEW

**Comment by mathurinm** [comment]
I removed fit_intercept=True testing (not supported yet, do you need it for this project?)

I used the datafit scaling by n_samples in the cython code to harmonize with both celer's lasso and sklearn's MTL.

Now the tests pass locally.

By the way do you know why Travis is not triggered?

**Comment by mathurinm** [comment]
I will configure travis to trigger builds for fork's PR. It is ongoing maintenance so I will do it later. Thank you @agramfort

**Comment by agramfort** [comment]
works for me !

do you want to activate CIs before merging to avoid breaking something?

**Comment by mathurinm** [comment]
yes :)

**Comment by agramfort** [comment]
push an empty line and let's see?

>

**Comment by ja-che** [comment]
Thanks for the help @mathurinm. In our experiment, we only need fit_intercept=False.

**Comment by agramfort** [comment]
@ja-che I am trying your code with the new code but so far not clear how
much it helps.

I may need @mathurinm to look :(

>

**Comment by mathurinm** [comment]
Keep me posted about the numericq if I can give it a more detailed look

**Pull request merged**
