### PR TITLE
FIX: make travis test both python versions

### PR DESCRIPTION
**Pull request by mathurinm**
@QB3

### CODE REVIEW

**Comment by mathurinm** [comment]
https://travis-ci.org/mathurinm/celer/jobs/508213201 super weird!

**Comment by mathurinm** [comment]
@agramfort this is baffling: the python version in the conda env is determined by the version of miniconda used, not by the one we specificy in `conda env create`. I don't know why.

**Comment by agramfort** [comment]
@QB3 also saw this. I don't know why. It's indeed weird as it has always worked.

**Comment by mathurinm** [comment]
Fixed @agramfort . The test suposed to fail, fails on each on the builds. Removing them and merging.

**Pull request merged**
