### PR TITLE
pass on doc

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by agramfort** [comment]
@mathurinm @josephsalmon please have a look.

now the finance data download does not work for me:

```
In [13]: %run plot_finance_path.py

=======================================================
Lasso path computation on Finance/log1p dataset
=======================================================

The example runs the Celer algorithm on the Finance dataset
which is a large sparse dataset.

Running time is here not compared with the scikit-learn
implementation as it makes the example too long to run.

*** Warning: this example may take more than 10 minutes to run ***
Downloading and preprocessing the Finance dataset...
*** Warning: This may take several minutes ***
Downloading data from https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/regression/log1p.E2006.train.bz2 (234.3 MB)


file_sizes:   8%|██▎                         | 20.7M/246M [09:03<08:03, 465KB/s]
file_sizes: 100%|█████████████████████████████| 246M/246M [08:22<00:00, 489KB/s]---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/work/src/celer/examples/plot_finance_path.py in <module>()
     33     print("Downloading and preprocessing the Finance dataset...")
     34     print("*** Warning: This may take several minutes ***")
---> 35     download_preprocess_finance()
     36
     37 print("Loading data...")

~/work/src/celer/celer/examples_utils/utils_finance.py in download_preprocess_finance()
     61     decompressed_path = "./data/log1p.E2006.train"
     62     if not os.path.isfile(decompressed_path):
---> 63         decompress_finance(compressed_path, decompressed_path)
     64
     65     y_path = "./data/finance_target_preprocessed"

~/work/src/celer/celer/examples_utils/utils_finance.py in decompress_finance(compressed_path, decompressed_path)
     19     decompressor = BZ2Decompressor()
     20     with open(decompressed_path, "wb") as f, open(compressed_path, "rb") as g:
---> 21         f.write(decompressor.decompress(g.read()))
     22
     23

OSError: [Errno 22] Invalid argument
```

**Comment by mathurinm** [comment]
I can't reproduce on my side. The decompressed data (`decompressor.decompress(g.read())`)  is 2.3 GB, can this be python having I/O trouble when writing files in the 2-4 GB range?

**Comment by josephsalmon** [comment]
May be put also a warning on the memory needed for the download of finance
. But I've never faced your pb Alex...

**Comment by agramfort** [comment]
ok it's working now with the last commit

**Pull request merged**
