### PR TITLE
[ENH] test climate download

### PR DESCRIPTION
**Pull request by mathurinm**
@agramfort do you know why the exception causing the test failure is not caught by the except block which follows ?
Error:
https://travis-ci.org/mathurinm/celer/builds/651959759#L822

from this block of code:
https://github.com/mathurinm/celer/blob/master/celer/datasets/climate.py#L112

The test pass locally after deleting the celer_data folder in my home

### CODE REVIEW

**Comment by agramfort** [comment]
I see a filenotfounderror. You don’t manage to reproduce?

**Comment by mathurinm** [comment]
There is indeed a filenotfounerror but it should precisely be caught
because it's in a try/except block

**Comment by agramfort** [comment]
I cannot replicate locally. Note that error is different in pr and push builds

**Comment by mathurinm** [comment]
OK there's a second exception occurring after, the climate dataset cannot be fetched on travis:
```
E           RuntimeError: Error while fetching file ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis.derived/surface/air.mon.mean.nc. Dataset fetching aborted.

E           Error: <urlopen error ftp error: timeout('timed out',)>
```
don't know why, it works fine locally

**Pull request closed without merging**
